server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firesystem?serverTimezone=CST
    username: root
    password: Administrator

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

mybatis:
  typeAliasesPackage: com.example.firesystemcs.entity
  mapperLocations: classpath:mapper/*.xml